### ISSUE TITLE
Individual agent training and benchmarking

### ISSUE THREAD

**Issue by shan18** [rvk007/Multi-Env-Decision-Making#4]
Train the agents for individual environments to determine the best config for each environment.

**Comment by rvk007** [comment]
After training Double DQN with various configurations, the following rewards were achieved:
- Highway: 26.75
- Merge: 12.18
- Roundabout: 9.3

These values are similar to the rewards found in various publications. The goal is to train a Multi-Env policy that also achieves rewards near to these values.
